version: "3.9"

networks:
  peloteras:
    name: peloteras
  nginx-proxy:
    name: nginx-proxy
    external: true

services:
  peloteras-front:
    container_name: peloteras-front
    image: peloteras/frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.production
    ports:
      - 3034:3000
    networks:
      - peloteras
      - nginx-proxy