-- =============================================================
-- Event check-ins: custom public links + registrations
-- =============================================================

CREATE TABLE IF NOT EXISTS public.event_checkin (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL,
  event_id    BIGINT NOT NULL REFERENCES public.event(id) ON DELETE CASCADE,
  created_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_active   BOOLEAN NOT NULL DEFAULT true,

  CONSTRAINT event_checkin_slug_format
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX IF NOT EXISTS event_checkin_slug_unique
  ON public.event_checkin (slug);

CREATE INDEX IF NOT EXISTS event_checkin_event_id_idx
  ON public.event_checkin (event_id);

CREATE INDEX IF NOT EXISTS event_checkin_created_by_idx
  ON public.event_checkin (created_by)
  WHERE created_by IS NOT NULL;


CREATE TABLE IF NOT EXISTS public.event_checkin_registration (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  checkin_id        BIGINT NOT NULL REFERENCES public.event_checkin(id) ON DELETE CASCADE,
  first_name        TEXT NOT NULL,
  last_name         TEXT NOT NULL,
  email             TEXT NOT NULL,
  email_normalized  TEXT NOT NULL,
  phone             TEXT NOT NULL,

  CONSTRAINT event_checkin_registration_unique_email
    UNIQUE (checkin_id, email_normalized)
);

CREATE INDEX IF NOT EXISTS event_checkin_registration_checkin_id_idx
  ON public.event_checkin_registration (checkin_id);

CREATE INDEX IF NOT EXISTS event_checkin_registration_created_at_idx
  ON public.event_checkin_registration (created_at DESC);
