create table if not exists "public"."wallet_provider_settings" (
  "id" bigint generated by default as identity not null,
  "provider" text not null,
  "issuer_id" text not null,
  "active_class_id" text,
  "service_account_email" text not null,
  "service_account_private_key" text not null,
  "origins" text[] not null default '{}'::text[],
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "updated_by" uuid,
  constraint "wallet_provider_settings_pkey" primary key ("id"),
  constraint "wallet_provider_settings_provider_key" unique ("provider"),
  constraint "wallet_provider_settings_provider_check" check ("provider" in ('google_wallet')),
  constraint "wallet_provider_settings_updated_by_fkey" foreign key ("updated_by") references "auth"."users"("id") on update cascade on delete set null
);

create index if not exists "wallet_provider_settings_provider_idx"
  on "public"."wallet_provider_settings" using btree ("provider");

alter table "public"."wallet_provider_settings" enable row level security;

create policy "wallet_provider_settings_service_role_all"
  on "public"."wallet_provider_settings"
  as permissive
  for all
  to service_role
  using (true)
  with check (true);
