-- TEAM-111: Team invitation model.
-- Prepares the data structure for future invitations by username, email and
-- team link. This migration intentionally does not implement UI or email
-- delivery.

CREATE TABLE IF NOT EXISTS public.team_invitation (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id            BIGINT NOT NULL REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  invited_by_user_id UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  invitee_user_id    UUID REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  invitee_email      TEXT,
  invitee_username   TEXT,
  delivery_method    TEXT NOT NULL DEFAULT 'link',
  status             TEXT NOT NULL DEFAULT 'pending',
  invitation_token   UUID NOT NULL DEFAULT extensions.gen_random_uuid(),
  metadata           JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at         TIMESTAMPTZ,
  responded_at       TIMESTAMPTZ,
  cancelled_at       TIMESTAMPTZ,
  accepted_member_id BIGINT REFERENCES public.team_member(id) ON UPDATE CASCADE ON DELETE SET NULL,

  CONSTRAINT team_invitation_delivery_method_check
    CHECK (delivery_method IN ('username', 'email', 'link')),
  CONSTRAINT team_invitation_status_check
    CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled', 'expired')),
  CONSTRAINT team_invitation_metadata_object_check
    CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT team_invitation_email_format_check
    CHECK (
      invitee_email IS NULL
      OR btrim(invitee_email) = ''
      OR invitee_email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
    ),
  CONSTRAINT team_invitation_username_format_check
    CHECK (
      invitee_username IS NULL
      OR btrim(invitee_username) = ''
      OR btrim(invitee_username) ~ '^[A-Za-z0-9._-]{2,40}$'
    ),
  CONSTRAINT team_invitation_direct_target_check
    CHECK (
      delivery_method = 'link'
      OR invitee_user_id IS NOT NULL
      OR NULLIF(btrim(invitee_email), '') IS NOT NULL
      OR NULLIF(btrim(invitee_username), '') IS NOT NULL
    ),
  CONSTRAINT team_invitation_response_timestamp_check
    CHECK (
      (status IN ('accepted', 'rejected') AND responded_at IS NOT NULL)
      OR (status NOT IN ('accepted', 'rejected'))
    ),
  CONSTRAINT team_invitation_cancel_timestamp_check
    CHECK (
      (status = 'cancelled' AND cancelled_at IS NOT NULL)
      OR status <> 'cancelled'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_token_unique_idx
  ON public.team_invitation (invitation_token);

CREATE INDEX IF NOT EXISTS team_invitation_team_id_idx
  ON public.team_invitation (team_id);

CREATE INDEX IF NOT EXISTS team_invitation_invited_by_user_id_idx
  ON public.team_invitation (invited_by_user_id);

CREATE INDEX IF NOT EXISTS team_invitation_invitee_user_id_idx
  ON public.team_invitation (invitee_user_id);

CREATE INDEX IF NOT EXISTS team_invitation_status_idx
  ON public.team_invitation (status);

CREATE INDEX IF NOT EXISTS team_invitation_pending_team_idx
  ON public.team_invitation (team_id, created_at DESC)
  WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_pending_link_unique_idx
  ON public.team_invitation (team_id)
  WHERE status = 'pending' AND delivery_method = 'link';

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_pending_user_unique_idx
  ON public.team_invitation (team_id, invitee_user_id)
  WHERE status = 'pending' AND invitee_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_pending_email_unique_idx
  ON public.team_invitation (team_id, lower(btrim(invitee_email)))
  WHERE status = 'pending' AND NULLIF(btrim(invitee_email), '') IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_pending_username_unique_idx
  ON public.team_invitation (team_id, lower(btrim(invitee_username)))
  WHERE status = 'pending' AND NULLIF(btrim(invitee_username), '') IS NOT NULL;

CREATE OR REPLACE FUNCTION public.set_team_invitation_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_team_invitation_updated_at ON public.team_invitation;

CREATE TRIGGER set_team_invitation_updated_at
BEFORE UPDATE ON public.team_invitation
FOR EACH ROW
EXECUTE FUNCTION public.set_team_invitation_updated_at();

CREATE OR REPLACE FUNCTION public.is_active_team_captain(
  p_team_id BIGINT,
  p_user_id UUID DEFAULT auth.uid()
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.team_member captain_membership
    JOIN public.team captain_team
      ON captain_team.id = captain_membership.team_id
    WHERE captain_membership.team_id = p_team_id
      AND captain_membership.user_id = p_user_id
      AND captain_membership.role = 'captain'
      AND captain_membership.status = 'active'
      AND captain_team.is_active = true
      AND captain_team.deleted_at IS NULL
  );
$$;

CREATE OR REPLACE FUNCTION public.create_team_invitation(
  p_team_id BIGINT,
  p_delivery_method TEXT DEFAULT 'link',
  p_invitee_user_id UUID DEFAULT NULL,
  p_invitee_email TEXT DEFAULT NULL,
  p_invitee_username TEXT DEFAULT NULL,
  p_expires_at TIMESTAMPTZ DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS SETOF public.team_invitation
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_delivery_method TEXT := lower(btrim(COALESCE(p_delivery_method, 'link')));
  v_invitee_email TEXT := lower(NULLIF(btrim(COALESCE(p_invitee_email, '')), ''));
  v_invitee_username TEXT := lower(NULLIF(btrim(COALESCE(p_invitee_username, '')), ''));
  v_invitee_user_id UUID := p_invitee_user_id;
  v_invitation public.team_invitation%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '28000';
  END IF;

  IF NOT public.is_active_team_captain(p_team_id, v_user_id) THEN
    RAISE EXCEPTION 'Only an active team captain can create invitations' USING ERRCODE = '42501';
  END IF;

  IF v_delivery_method NOT IN ('username', 'email', 'link') THEN
    RAISE EXCEPTION 'Invalid invitation delivery method' USING ERRCODE = '23514';
  END IF;

  IF v_delivery_method = 'username' AND v_invitee_username IS NULL THEN
    RAISE EXCEPTION 'Username invitation requires invitee_username' USING ERRCODE = '23514';
  END IF;

  IF v_delivery_method = 'email' AND v_invitee_email IS NULL THEN
    RAISE EXCEPTION 'Email invitation requires invitee_email' USING ERRCODE = '23514';
  END IF;

  IF v_delivery_method = 'username' AND v_invitee_user_id IS NULL THEN
    SELECT profile.user
    INTO v_invitee_user_id
    FROM public.profile profile
    WHERE lower(btrim(profile.username)) = v_invitee_username
    LIMIT 1;
  END IF;

  IF v_invitee_user_id = v_user_id THEN
    RAISE EXCEPTION 'Captain cannot invite herself' USING ERRCODE = '23514';
  END IF;

  IF v_invitee_user_id IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.team_member existing_member
    WHERE existing_member.team_id = p_team_id
      AND existing_member.user_id = v_invitee_user_id
      AND existing_member.status = 'active'
  ) THEN
    RAISE EXCEPTION 'User is already an active team member' USING ERRCODE = '23505';
  END IF;

  INSERT INTO public.team_invitation (
    team_id,
    invited_by_user_id,
    invitee_user_id,
    invitee_email,
    invitee_username,
    delivery_method,
    expires_at,
    metadata
  )
  VALUES (
    p_team_id,
    v_user_id,
    v_invitee_user_id,
    v_invitee_email,
    v_invitee_username,
    v_delivery_method,
    p_expires_at,
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING * INTO v_invitation;

  RETURN QUERY
  SELECT *
  FROM public.team_invitation created_invitation
  WHERE created_invitation.id = v_invitation.id;
END;
$$;

ALTER TABLE public.team_invitation ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.team_invitation TO authenticated;
GRANT ALL ON public.team_invitation TO service_role;

REVOKE INSERT, UPDATE, DELETE ON public.team_invitation FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.is_active_team_captain(BIGINT, UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_team_invitation(BIGINT, TEXT, UUID, TEXT, TEXT, TIMESTAMPTZ, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_active_team_captain(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_team_invitation(BIGINT, TEXT, UUID, TEXT, TEXT, TIMESTAMPTZ, JSONB) TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'team_invitation'
      AND policyname = 'team_invitation_captain_select'
  ) THEN
    CREATE POLICY team_invitation_captain_select
      ON public.team_invitation
      AS PERMISSIVE
      FOR SELECT
      TO authenticated
      USING (public.is_active_team_captain(team_id, auth.uid()));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'team_invitation'
      AND policyname = 'team_invitation_invitee_select'
  ) THEN
    CREATE POLICY team_invitation_invitee_select
      ON public.team_invitation
      AS PERMISSIVE
      FOR SELECT
      TO authenticated
      USING (auth.uid() = invitee_user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'team_invitation'
      AND policyname = 'team_invitation_service_role_all'
  ) THEN
    CREATE POLICY team_invitation_service_role_all
      ON public.team_invitation
      AS PERMISSIVE
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

COMMENT ON TABLE public.team_invitation IS
  'Team invitation/convocatoria records for future username, email and link flows.';

COMMENT ON COLUMN public.team_invitation.delivery_method IS
  'How the invitation was initiated. Allowed values: username, email, link.';

COMMENT ON COLUMN public.team_invitation.status IS
  'Invitation lifecycle. Allowed values: pending, accepted, rejected, cancelled, expired.';

COMMENT ON COLUMN public.team_invitation.invitation_token IS
  'Unique token for accepting/rejecting a specific invitation in future UI flows.';

COMMENT ON FUNCTION public.create_team_invitation(BIGINT, TEXT, UUID, TEXT, TEXT, TIMESTAMPTZ, JSONB) IS
  'Creates a pending team invitation when auth.uid() is an active captain of the team.';
