create table if not exists "public"."product_analytics_events" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "event_name" text not null,
  "user_id" uuid,
  "event_id" bigint,
  "ref_user_id" uuid,
  "source" text not null default 'web'::text,
  "channel" text,
  "user_agent" text,
  "ip_address" text,
  "payload" jsonb not null default '{}'::jsonb,
  constraint "product_analytics_events_pkey" primary key ("id"),
  constraint "product_analytics_events_user_id_fkey"
    foreign key ("user_id") references "auth"."users"("id")
    on update cascade on delete set null,
  constraint "product_analytics_events_ref_user_id_fkey"
    foreign key ("ref_user_id") references "auth"."users"("id")
    on update cascade on delete set null,
  constraint "product_analytics_events_event_id_fkey"
    foreign key ("event_id") references "public"."event"("id")
    on update cascade on delete set null
);

create index if not exists "product_analytics_events_event_name_idx"
  on "public"."product_analytics_events" using btree ("event_name");

create index if not exists "product_analytics_events_created_at_idx"
  on "public"."product_analytics_events" using btree ("created_at" desc);

create index if not exists "product_analytics_events_event_id_idx"
  on "public"."product_analytics_events" using btree ("event_id");

create index if not exists "product_analytics_events_ref_user_id_idx"
  on "public"."product_analytics_events" using btree ("ref_user_id");

alter table "public"."product_analytics_events" enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'product_analytics_events'
      and policyname = 'product_analytics_events_public_insert'
  ) then
    create policy "product_analytics_events_public_insert"
      on "public"."product_analytics_events"
      as permissive
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'product_analytics_events'
      and policyname = 'product_analytics_events_service_role_all'
  ) then
    create policy "product_analytics_events_service_role_all"
      on "public"."product_analytics_events"
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
