-- Equipo destacado, administración de capitana e inscripción grupal.

ALTER TABLE public.profile
  ADD COLUMN IF NOT EXISTS featured_team_id BIGINT
  REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS profile_featured_team_id_idx
  ON public.profile(featured_team_id)
  WHERE featured_team_id IS NOT NULL;

ALTER TABLE public.event
  ADD COLUMN IF NOT EXISTS allows_team_registration BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS team_registration_min_players SMALLINT,
  ADD COLUMN IF NOT EXISTS team_registration_max_players SMALLINT;

ALTER TABLE public.event
  DROP CONSTRAINT IF EXISTS event_team_registration_limits_check;

ALTER TABLE public.event
  ADD CONSTRAINT event_team_registration_limits_check CHECK (
    (team_registration_min_players IS NULL OR team_registration_min_players > 0)
    AND (team_registration_max_players IS NULL OR team_registration_max_players > 0)
    AND (
      team_registration_min_players IS NULL
      OR team_registration_max_players IS NULL
      OR team_registration_min_players <= team_registration_max_players
    )
  );

CREATE TABLE IF NOT EXISTS public.team_event_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_id BIGINT NOT NULL REFERENCES public.event(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  team_id BIGINT NOT NULL REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  registered_by_user_id UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  operation_number TEXT NOT NULL,
  unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
  participant_count INTEGER NOT NULL CHECK (participant_count > 0),
  total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
  state TEXT NOT NULL DEFAULT 'pending'
    CHECK (state IN ('pending', 'approved', 'rejected', 'cancelled')),
  reviewed_at TIMESTAMPTZ,
  reviewed_by_user_id UUID REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  reject_reason TEXT,
  CONSTRAINT team_event_registration_operation_number_check
    CHECK (operation_number ~ '^[0-9]{8}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS team_event_registration_active_team_event_idx
  ON public.team_event_registration(event_id, team_id)
  WHERE state IN ('pending', 'approved');

CREATE INDEX IF NOT EXISTS team_event_registration_event_state_idx
  ON public.team_event_registration(event_id, state, created_at DESC);

CREATE INDEX IF NOT EXISTS team_event_registration_team_state_idx
  ON public.team_event_registration(team_id, state, created_at DESC);

ALTER TABLE public.assistants
  ADD COLUMN IF NOT EXISTS team_event_registration_id BIGINT
    REFERENCES public.team_event_registration(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS team_id BIGINT
    REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS assistants_team_event_registration_idx
  ON public.assistants(team_event_registration_id)
  WHERE team_event_registration_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS assistants_team_event_idx
  ON public.assistants(team_id, event)
  WHERE team_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.team_event_registration_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  registration_id BIGINT NOT NULL
    REFERENCES public.team_event_registration(id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_member_id BIGINT NOT NULL
    REFERENCES public.team_member(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  assistant_id BIGINT NOT NULL
    REFERENCES public.assistants(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
  CONSTRAINT team_event_registration_member_user_unique UNIQUE (registration_id, user_id),
  CONSTRAINT team_event_registration_member_assistant_unique UNIQUE (assistant_id)
);

CREATE INDEX IF NOT EXISTS team_event_registration_member_user_idx
  ON public.team_event_registration_member(user_id, registration_id);

CREATE OR REPLACE FUNCTION public.set_team_event_registration_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_team_event_registration_updated_at
  ON public.team_event_registration;
CREATE TRIGGER set_team_event_registration_updated_at
BEFORE UPDATE ON public.team_event_registration
FOR EACH ROW EXECUTE FUNCTION public.set_team_event_registration_updated_at();

ALTER TABLE public.team_event_registration ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_event_registration_member ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.team_event_registration FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.team_event_registration_member FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.team_event_registration TO service_role;
GRANT ALL ON public.team_event_registration_member TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

DROP POLICY IF EXISTS team_event_registration_service_role_all
  ON public.team_event_registration;
CREATE POLICY team_event_registration_service_role_all
  ON public.team_event_registration
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS team_event_registration_member_service_role_all
  ON public.team_event_registration_member;
CREATE POLICY team_event_registration_member_service_role_all
  ON public.team_event_registration_member
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.set_featured_team(p_team_id BIGINT DEFAULT NULL)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF p_team_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.team_member member
    JOIN public.team team ON team.id = member.team_id
    WHERE member.team_id = p_team_id
      AND member.user_id = v_user_id
      AND member.status = 'active'
      AND team.is_active = true
      AND team.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'FEATURED_TEAM_MEMBERSHIP_REQUIRED';
  END IF;

  UPDATE public.profile
  SET featured_team_id = p_team_id
  WHERE "user" = v_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'PROFILE_NOT_FOUND';
  END IF;

  RETURN p_team_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_team_as_captain(
  p_team_id BIGINT,
  p_name TEXT,
  p_avatar_url TEXT DEFAULT NULL,
  p_instagram_username TEXT DEFAULT NULL,
  p_tiktok_username TEXT DEFAULT NULL
)
RETURNS public.team
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_team public.team%ROWTYPE;
  v_name TEXT := btrim(COALESCE(p_name, ''));
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF char_length(v_name) NOT BETWEEN 2 AND 80 THEN
    RAISE EXCEPTION 'TEAM_NAME_INVALID';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.team_member member
    WHERE member.team_id = p_team_id
      AND member.user_id = v_user_id
      AND member.role = 'captain'
      AND member.status = 'active'
  ) THEN
    RAISE EXCEPTION 'CAPTAIN_REQUIRED';
  END IF;

  UPDATE public.team
  SET name = v_name,
      avatar_url = NULLIF(btrim(COALESCE(p_avatar_url, '')), ''),
      instagram_username = NULLIF(regexp_replace(btrim(COALESCE(p_instagram_username, '')), '^@+', ''), ''),
      tiktok_username = NULLIF(regexp_replace(btrim(COALESCE(p_tiktok_username, '')), '^@+', ''), '')
  WHERE id = p_team_id AND is_active = true AND deleted_at IS NULL
  RETURNING * INTO v_team;

  IF v_team.id IS NULL THEN RAISE EXCEPTION 'TEAM_NOT_FOUND'; END IF;
  RETURN v_team;
END;
$$;

CREATE OR REPLACE FUNCTION public.remove_team_member(
  p_team_id BIGINT,
  p_member_id BIGINT
)
RETURNS public.team_member
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_member public.team_member%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.team_member captain
    WHERE captain.team_id = p_team_id AND captain.user_id = v_user_id
      AND captain.role = 'captain' AND captain.status = 'active'
  ) THEN RAISE EXCEPTION 'CAPTAIN_REQUIRED'; END IF;

  SELECT * INTO v_member FROM public.team_member
  WHERE id = p_member_id AND team_id = p_team_id FOR UPDATE;
  IF v_member.id IS NULL OR v_member.status <> 'active' THEN
    RAISE EXCEPTION 'ACTIVE_MEMBER_NOT_FOUND';
  END IF;
  IF v_member.role = 'captain' THEN RAISE EXCEPTION 'CANNOT_REMOVE_CAPTAIN'; END IF;

  UPDATE public.team_member
  SET status = 'removed', ended_at = now()
  WHERE id = p_member_id RETURNING * INTO v_member;

  UPDATE public.profile SET featured_team_id = NULL
  WHERE "user" = v_member.user_id AND featured_team_id = p_team_id;
  RETURN v_member;
END;
$$;

CREATE OR REPLACE FUNCTION public.transfer_team_captain(
  p_team_id BIGINT,
  p_new_captain_member_id BIGINT
)
RETURNS public.team_member
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_current public.team_member%ROWTYPE;
  v_next public.team_member%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;

  SELECT * INTO v_current FROM public.team_member
  WHERE team_id = p_team_id AND user_id = v_user_id
    AND role = 'captain' AND status = 'active' FOR UPDATE;
  IF v_current.id IS NULL THEN RAISE EXCEPTION 'CAPTAIN_REQUIRED'; END IF;

  SELECT * INTO v_next FROM public.team_member
  WHERE id = p_new_captain_member_id AND team_id = p_team_id
    AND status = 'active' FOR UPDATE;
  IF v_next.id IS NULL THEN RAISE EXCEPTION 'ACTIVE_MEMBER_NOT_FOUND'; END IF;
  IF v_next.id = v_current.id THEN RETURN v_current; END IF;

  UPDATE public.team_member SET role = 'player' WHERE id = v_current.id;
  UPDATE public.team_member SET role = 'captain' WHERE id = v_next.id RETURNING * INTO v_next;
  RETURN v_next;
END;
$$;

CREATE OR REPLACE FUNCTION public.leave_team(p_team_id BIGINT)
RETURNS public.team_member
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_member public.team_member%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  SELECT * INTO v_member FROM public.team_member
  WHERE team_id = p_team_id AND user_id = v_user_id AND status = 'active' FOR UPDATE;
  IF v_member.id IS NULL THEN RAISE EXCEPTION 'ACTIVE_MEMBER_NOT_FOUND'; END IF;
  IF v_member.role = 'captain' THEN RAISE EXCEPTION 'CAPTAIN_CANNOT_LEAVE'; END IF;

  UPDATE public.team_member SET status = 'left', ended_at = now()
  WHERE id = v_member.id RETURNING * INTO v_member;
  UPDATE public.profile SET featured_team_id = NULL
  WHERE "user" = v_user_id AND featured_team_id = p_team_id;
  RETURN v_member;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_team_event_registration(
  p_event_id BIGINT,
  p_team_id BIGINT,
  p_member_user_ids UUID[],
  p_operation_number TEXT
)
RETURNS public.team_event_registration
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_event public.event%ROWTYPE;
  v_team public.team%ROWTYPE;
  v_registration public.team_event_registration%ROWTYPE;
  v_member public.team_member%ROWTYPE;
  v_member_user_id UUID;
  v_assistant_id BIGINT;
  v_selected_count INTEGER;
  v_active_count INTEGER;
  v_occupied_count INTEGER;
  v_min_players INTEGER;
  v_max_players INTEGER;
  v_unit_price NUMERIC;
  v_operation_number TEXT := btrim(COALESCE(p_operation_number, ''));
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF v_operation_number !~ '^[0-9]{8}$' THEN RAISE EXCEPTION 'OPERATION_NUMBER_INVALID'; END IF;
  IF p_member_user_ids IS NULL OR cardinality(p_member_user_ids) = 0 THEN
    RAISE EXCEPTION 'TEAM_MEMBERS_REQUIRED';
  END IF;

  SELECT count(*), count(DISTINCT member_id)
  INTO v_selected_count, v_active_count
  FROM unnest(p_member_user_ids) AS selected(member_id);
  IF v_selected_count <> v_active_count THEN RAISE EXCEPTION 'DUPLICATE_TEAM_MEMBER'; END IF;

  SELECT * INTO v_event FROM public.event WHERE id = p_event_id FOR UPDATE;
  IF v_event.id IS NULL OR v_event.is_published = false THEN RAISE EXCEPTION 'EVENT_NOT_AVAILABLE'; END IF;
  IF NOT v_event.allows_team_registration THEN RAISE EXCEPTION 'TEAM_REGISTRATION_DISABLED'; END IF;
  IF COALESCE(v_event.end_time, v_event.start_time) <= now() THEN RAISE EXCEPTION 'EVENT_ENDED'; END IF;

  SELECT * INTO v_team FROM public.team
  WHERE id = p_team_id AND is_active = true AND deleted_at IS NULL FOR UPDATE;
  IF v_team.id IS NULL THEN RAISE EXCEPTION 'TEAM_NOT_FOUND'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.team_member captain
    WHERE captain.team_id = p_team_id AND captain.user_id = v_user_id
      AND captain.role = 'captain' AND captain.status = 'active'
  ) THEN RAISE EXCEPTION 'CAPTAIN_REQUIRED'; END IF;

  SELECT count(*) INTO v_active_count
  FROM public.team_member member
  WHERE member.team_id = p_team_id AND member.status = 'active'
    AND member.user_id = ANY(p_member_user_ids);
  IF v_active_count <> v_selected_count THEN RAISE EXCEPTION 'ACTIVE_TEAM_MEMBERS_REQUIRED'; END IF;

  v_min_players := COALESCE(v_event.team_registration_min_players, 2);
  v_max_players := COALESCE(v_event.team_registration_max_players, v_event.max_users, 1000);
  IF v_selected_count < v_min_players OR v_selected_count > v_max_players THEN
    RAISE EXCEPTION 'TEAM_SIZE_OUT_OF_RANGE';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.team_event_registration registration
    WHERE registration.event_id = p_event_id AND registration.team_id = p_team_id
      AND registration.state IN ('pending', 'approved')
  ) THEN RAISE EXCEPTION 'TEAM_ALREADY_REGISTERED'; END IF;

  IF EXISTS (
    SELECT 1 FROM public.assistants assistant
    WHERE assistant.event = p_event_id
      AND assistant.user = ANY(p_member_user_ids)
      AND lower(COALESCE(assistant.state, '')) IN ('pending', 'approved')
  ) THEN RAISE EXCEPTION 'MEMBER_ALREADY_REGISTERED'; END IF;

  SELECT count(*) INTO v_occupied_count
  FROM public.assistants assistant
  WHERE assistant.event = p_event_id
    AND lower(COALESCE(assistant.state, '')) IN ('pending', 'approved');
  IF COALESCE(v_event.max_users, 0) > 0
     AND v_occupied_count + v_selected_count > v_event.max_users THEN
    RAISE EXCEPTION 'EVENT_SOLD_OUT';
  END IF;

  v_unit_price := COALESCE(v_event.price, 0);
  INSERT INTO public.team_event_registration (
    event_id, team_id, registered_by_user_id, operation_number,
    unit_price, participant_count, total_amount, state
  ) VALUES (
    p_event_id, p_team_id, v_user_id, v_operation_number,
    v_unit_price, v_selected_count, v_unit_price * v_selected_count, 'pending'
  ) RETURNING * INTO v_registration;

  FOREACH v_member_user_id IN ARRAY p_member_user_ids LOOP
    SELECT * INTO v_member FROM public.team_member
    WHERE team_id = p_team_id AND user_id = v_member_user_id AND status = 'active';

    INSERT INTO public.assistants (
      event, "user", "operationNumber", state, team_event_registration_id, team_id
    ) VALUES (
      p_event_id, v_member_user_id, v_operation_number::BIGINT, 'pending', v_registration.id, p_team_id
    ) RETURNING id INTO v_assistant_id;

    INSERT INTO public.team_event_registration_member (
      registration_id, team_member_id, user_id, assistant_id, unit_price
    ) VALUES (
      v_registration.id, v_member.id, v_member_user_id, v_assistant_id, v_unit_price
    );
  END LOOP;

  RETURN v_registration;
END;
$$;

CREATE OR REPLACE FUNCTION public.review_team_event_registration(
  p_registration_id BIGINT,
  p_decision TEXT,
  p_reviewer_user_id UUID,
  p_reject_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_registration public.team_event_registration%ROWTYPE;
  v_event public.event%ROWTYPE;
  v_decision TEXT := lower(btrim(COALESCE(p_decision, '')));
  v_approved_count INTEGER;
  v_assistant_ids BIGINT[];
BEGIN
  IF v_decision NOT IN ('approve', 'reject') THEN RAISE EXCEPTION 'REVIEW_DECISION_INVALID'; END IF;
  SELECT * INTO v_registration FROM public.team_event_registration
  WHERE id = p_registration_id FOR UPDATE;
  IF v_registration.id IS NULL THEN RAISE EXCEPTION 'TEAM_REGISTRATION_NOT_FOUND'; END IF;

  IF v_registration.state NOT IN ('pending', CASE WHEN v_decision = 'approve' THEN 'approved' ELSE 'rejected' END) THEN
    RAISE EXCEPTION 'TEAM_REGISTRATION_ALREADY_REVIEWED';
  END IF;

  SELECT array_agg(member.assistant_id ORDER BY member.assistant_id)
  INTO v_assistant_ids
  FROM public.team_event_registration_member member
  WHERE member.registration_id = v_registration.id;

  IF v_decision = 'approve' THEN
    SELECT * INTO v_event FROM public.event WHERE id = v_registration.event_id FOR UPDATE;
    SELECT count(*) INTO v_approved_count FROM public.assistants assistant
    WHERE assistant.event = v_registration.event_id
      AND lower(COALESCE(assistant.state, '')) = 'approved'
      AND assistant.team_event_registration_id IS DISTINCT FROM v_registration.id;
    IF COALESCE(v_event.max_users, 0) > 0
       AND v_approved_count + v_registration.participant_count > v_event.max_users THEN
      RAISE EXCEPTION 'EVENT_SOLD_OUT';
    END IF;

    UPDATE public.assistants SET state = 'approved'
    WHERE team_event_registration_id = v_registration.id;
    UPDATE public.team_event_registration
    SET state = 'approved', reviewed_at = COALESCE(reviewed_at, now()),
        reviewed_by_user_id = COALESCE(reviewed_by_user_id, p_reviewer_user_id), reject_reason = NULL
    WHERE id = v_registration.id;

    INSERT INTO public.ticket (
      assistant_id, event_id, user_id, status, qr_token
    )
    SELECT assistant.id, assistant.event, assistant."user", 'active',
           encode(extensions.gen_random_bytes(24), 'hex')
    FROM public.assistants assistant
    WHERE assistant.team_event_registration_id = v_registration.id
    ON CONFLICT (event_id, user_id) DO UPDATE
    SET assistant_id = EXCLUDED.assistant_id,
        status = CASE WHEN public.ticket.status = 'used' THEN 'used' ELSE 'active' END,
        updated_at = now();
  ELSE
    UPDATE public.assistants SET state = 'rejected'
    WHERE team_event_registration_id = v_registration.id;
    UPDATE public.team_event_registration
    SET state = 'rejected', reviewed_at = COALESCE(reviewed_at, now()),
        reviewed_by_user_id = COALESCE(reviewed_by_user_id, p_reviewer_user_id),
        reject_reason = NULLIF(btrim(COALESCE(p_reject_reason, '')), '')
    WHERE id = v_registration.id;
    UPDATE public.ticket SET status = 'revoked', updated_at = now()
    WHERE assistant_id = ANY(COALESCE(v_assistant_ids, ARRAY[]::BIGINT[])) AND status <> 'used';
  END IF;

  RETURN jsonb_build_object(
    'registrationId', v_registration.id,
    'state', CASE WHEN v_decision = 'approve' THEN 'approved' ELSE 'rejected' END,
    'assistantIds', COALESCE(to_jsonb(v_assistant_ids), '[]'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_team_as_captain(p_team_id BIGINT)
RETURNS public.team
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_team public.team%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.team_member captain
    WHERE captain.team_id = p_team_id AND captain.user_id = v_user_id
      AND captain.role = 'captain' AND captain.status = 'active'
  ) THEN RAISE EXCEPTION 'CAPTAIN_REQUIRED'; END IF;

  IF EXISTS (
    SELECT 1 FROM public.team_event_registration registration
    JOIN public.event event ON event.id = registration.event_id
    WHERE registration.team_id = p_team_id
      AND (registration.state = 'pending'
        OR (registration.state = 'approved' AND COALESCE(event.end_time, event.start_time) >= now()))
  ) THEN RAISE EXCEPTION 'TEAM_HAS_ACTIVE_EVENT_REGISTRATIONS'; END IF;

  UPDATE public.team SET is_active = false, deleted_at = now()
  WHERE id = p_team_id AND is_active = true AND deleted_at IS NULL
  RETURNING * INTO v_team;
  IF v_team.id IS NULL THEN RAISE EXCEPTION 'TEAM_NOT_FOUND'; END IF;

  UPDATE public.team_member SET status = 'removed', ended_at = now()
  WHERE team_id = p_team_id AND status = 'active';
  UPDATE public.profile SET featured_team_id = NULL WHERE featured_team_id = p_team_id;
  UPDATE public.team_invitation
  SET status = 'cancelled', cancelled_at = now(), responded_at = COALESCE(responded_at, now())
  WHERE team_id = p_team_id AND status = 'pending';
  RETURN v_team;
END;
$$;

CREATE OR REPLACE FUNCTION public.clear_invalid_featured_team_for_member()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' OR NEW.status <> 'active' THEN
    UPDATE public.profile SET featured_team_id = NULL
    WHERE "user" = OLD.user_id AND featured_team_id = OLD.team_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS clear_invalid_featured_team_for_member ON public.team_member;
CREATE TRIGGER clear_invalid_featured_team_for_member
AFTER UPDATE OF status OR DELETE ON public.team_member
FOR EACH ROW EXECUTE FUNCTION public.clear_invalid_featured_team_for_member();

CREATE OR REPLACE FUNCTION public.clear_invalid_featured_team_for_team()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.is_active = false OR NEW.deleted_at IS NOT NULL THEN
    UPDATE public.profile SET featured_team_id = NULL WHERE featured_team_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS clear_invalid_featured_team_for_team ON public.team;
CREATE TRIGGER clear_invalid_featured_team_for_team
AFTER UPDATE OF is_active, deleted_at ON public.team
FOR EACH ROW EXECUTE FUNCTION public.clear_invalid_featured_team_for_team();

REVOKE ALL ON FUNCTION public.set_featured_team(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.update_team_as_captain(BIGINT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.remove_team_member(BIGINT, BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.transfer_team_captain(BIGINT, BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.leave_team(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_team_event_registration(BIGINT, BIGINT, UUID[], TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_team_as_captain(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.review_team_event_registration(BIGINT, TEXT, UUID, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.set_featured_team(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_team_as_captain(BIGINT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.remove_team_member(BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_team_captain(BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_team(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_team_event_registration(BIGINT, BIGINT, UUID[], TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_team_as_captain(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.review_team_event_registration(BIGINT, TEXT, UUID, TEXT) TO service_role;

COMMENT ON COLUMN public.profile.featured_team_id IS
  'Equipo activo destacado por la jugadora en su cuenta y navegación.';
COMMENT ON TABLE public.team_event_registration IS
  'Pago e inscripción grupal creada por la capitana para un evento.';
COMMENT ON TABLE public.team_event_registration_member IS
  'Participantes, asistentes y precio unitario congelados para una inscripción grupal.';
