-- =============================================================
-- Coupon system: tables, constraints, and indexes
-- =============================================================

-- 1. Coupon definitions
CREATE TABLE IF NOT EXISTS public.coupon (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  discount_amount NUMERIC NOT NULL CHECK (discount_amount > 0),
  event_id    BIGINT REFERENCES public.event(id) ON DELETE SET NULL,
  type        TEXT NOT NULL CHECK (type IN ('company', 'individual')),
  company_name TEXT,
  assigned_email TEXT,
  max_uses    INTEGER NOT NULL CHECK (max_uses > 0),
  current_uses INTEGER NOT NULL DEFAULT 0 CHECK (current_uses >= 0),
  is_active   BOOLEAN NOT NULL DEFAULT true,
  expires_at  TIMESTAMPTZ,
  created_by  UUID NOT NULL REFERENCES auth.users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Individual coupons must have assigned_email
  CONSTRAINT coupon_individual_requires_email
    CHECK (type <> 'individual' OR assigned_email IS NOT NULL),

  -- Company coupons must have company_name
  CONSTRAINT coupon_company_requires_name
    CHECK (type <> 'company' OR company_name IS NOT NULL)
);

-- Code must be unique (case-insensitive)
CREATE UNIQUE INDEX coupon_code_unique ON public.coupon (LOWER(code));

-- Fast lookups by event
CREATE INDEX coupon_event_id_idx ON public.coupon (event_id) WHERE event_id IS NOT NULL;

-- Fast lookups for active coupons
CREATE INDEX coupon_active_idx ON public.coupon (is_active) WHERE is_active = true;


-- 2. Coupon redemptions (usage tracking + reimbursement)
CREATE TABLE IF NOT EXISTS public.coupon_redemption (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id            BIGINT NOT NULL REFERENCES public.coupon(id) ON DELETE CASCADE,
  user_id              UUID NOT NULL REFERENCES auth.users(id),
  event_id             BIGINT NOT NULL REFERENCES public.event(id),
  assistant_id         BIGINT REFERENCES public.assistants(id) ON DELETE SET NULL,
  discount_applied     NUMERIC NOT NULL CHECK (discount_applied > 0),
  organizer_user_id    UUID NOT NULL REFERENCES auth.users(id),
  reimbursement_status TEXT NOT NULL DEFAULT 'pending' CHECK (reimbursement_status IN ('pending', 'deposited')),
  reimbursed_at        TIMESTAMPTZ,
  reimbursed_by        UUID REFERENCES auth.users(id),
  redeemed_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One coupon per user per event
  CONSTRAINT coupon_redemption_unique UNIQUE (coupon_id, user_id, event_id)
);

-- Fast lookups for pending reimbursements
CREATE INDEX coupon_redemption_pending_idx
  ON public.coupon_redemption (reimbursement_status)
  WHERE reimbursement_status = 'pending';

-- Fast lookups by event
CREATE INDEX coupon_redemption_event_idx ON public.coupon_redemption (event_id);

-- Fast lookups by organizer (for admin payment views)
CREATE INDEX coupon_redemption_organizer_idx ON public.coupon_redemption (organizer_user_id);

-- Fast lookups by assistant (for joining with payments)
CREATE INDEX coupon_redemption_assistant_idx ON public.coupon_redemption (assistant_id) WHERE assistant_id IS NOT NULL;
