-- drop extension if exists "pg_net";

-- set check_function_bodies = off;

-- CREATE OR REPLACE FUNCTION extensions.grant_pg_cron_access()
--  RETURNS event_trigger
--  LANGUAGE plpgsql
-- AS $function$
-- BEGIN
--   IF EXISTS (
--     SELECT
--     FROM pg_event_trigger_ddl_commands() AS ev
--     JOIN pg_extension AS ext
--     ON ev.objid = ext.oid
--     WHERE ext.extname = 'pg_cron'
--   )
--   THEN
--     grant usage on schema cron to postgres with grant option;

--     alter default privileges in schema cron grant all on tables to postgres with grant option;
--     alter default privileges in schema cron grant all on functions to postgres with grant option;
--     alter default privileges in schema cron grant all on sequences to postgres with grant option;

--     alter default privileges for user supabase_admin in schema cron grant all
--         on sequences to postgres with grant option;
--     alter default privileges for user supabase_admin in schema cron grant all
--         on tables to postgres with grant option;
--     alter default privileges for user supabase_admin in schema cron grant all
--         on functions to postgres with grant option;

--     grant all privileges on all tables in schema cron to postgres with grant option;
--     revoke all on table cron.job from postgres;
--     grant select on table cron.job to postgres with grant option;
--   END IF;
-- END;
-- $function$
-- ;

-- CREATE OR REPLACE FUNCTION extensions.grant_pg_net_access()
--  RETURNS event_trigger
--  LANGUAGE plpgsql
-- AS $function$
--   BEGIN
--     IF EXISTS (
--       SELECT 1
--       FROM pg_event_trigger_ddl_commands() AS ev
--       JOIN pg_extension AS ext
--       ON ev.objid = ext.oid
--       WHERE ext.extname = 'pg_net'
--     )
--     THEN
--       IF NOT EXISTS (
--         SELECT 1
--         FROM pg_roles
--         WHERE rolname = 'supabase_functions_admin'
--       )
--       THEN
--         CREATE USER supabase_functions_admin NOINHERIT CREATEROLE LOGIN NOREPLICATION;
--       END IF;

--       GRANT USAGE ON SCHEMA net TO supabase_functions_admin, postgres, anon, authenticated, service_role;

--       IF EXISTS (
--         SELECT FROM pg_extension
--         WHERE extname = 'pg_net'
--         -- all versions in use on existing projects as of 2025-02-20
--         -- version 0.12.0 onwards don't need these applied
--         AND extversion IN ('0.2', '0.6', '0.7', '0.7.1', '0.8.0', '0.10.0', '0.11.0')
--       ) THEN
--         ALTER function net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;
--         ALTER function net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;

--         ALTER function net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) SET search_path = net;
--         ALTER function net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) SET search_path = net;

--         REVOKE ALL ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;
--         REVOKE ALL ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;

--         GRANT EXECUTE ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role;
--         GRANT EXECUTE ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role;
--       END IF;
--     END IF;
--   END;
--   $function$
-- ;

create sequence "public"."profile_position_id_seq";


  create table "public"."assistants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event" bigint,
    "user" uuid,
    "operationNumber" bigint,
    "state" text
      );



  create table "public"."event" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying,
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "location" jsonb,
    "location_text" text,
    "max_users" smallint,
    "min_users" smallint,
    "price" numeric,
    "description" jsonb,
    "district" text,
    "EventType" bigint,
    "created_by" text,
    "created_by_id" uuid,
    "level" bigint
      );



  create table "public"."eventFeatures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event" bigint,
    "feature" bigint
      );



  create table "public"."eventType" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "event" bigint
      );



  create table "public"."features" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
      );



  create table "public"."level" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
      );



  create table "public"."otherFeatures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "event" bigint
      );



  create table "public"."paymentMethod" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "QR" text,
    "number" numeric,
    "user" uuid,
    "type" character varying,
    "event" bigint
      );



  create table "public"."player_position" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
      );



  create table "public"."profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user" uuid,
    "username" text not null,
    "level_id" bigint,
    "onboarding_step" numeric,
    "is_profile_complete" boolean
      );



  create table "public"."profile_position" (
    "id" integer not null default nextval('public.profile_position_id_seq'::regclass),
    "profile_id" integer not null,
    "position_id" integer not null
      );



  create table "public"."waitlist_emails" (
    "id" uuid not null default gen_random_uuid(),
    "email" text not null,
    "source" text default 'coming_soon'::text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."waitlist_emails" enable row level security;

alter sequence "public"."profile_position_id_seq" owned by "public"."profile_position"."id";

CREATE UNIQUE INDEX assistants_pkey ON public.assistants USING btree (id);

CREATE UNIQUE INDEX "eventFeatures_pkey" ON public."eventFeatures" USING btree (id);

CREATE UNIQUE INDEX "eventType_pkey" ON public."eventType" USING btree (id);

CREATE UNIQUE INDEX event_id_key ON public.event USING btree (id);

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

CREATE UNIQUE INDEX features_pkey ON public.features USING btree (id);

CREATE UNIQUE INDEX level_name_key ON public.level USING btree (name);

CREATE UNIQUE INDEX level_pkey ON public.level USING btree (id);

CREATE UNIQUE INDEX "otherFeatures_pkey" ON public."otherFeatures" USING btree (id);

CREATE UNIQUE INDEX "paymentMethod_pkey" ON public."paymentMethod" USING btree (id);

CREATE UNIQUE INDEX player_position_id_key ON public.player_position USING btree (id);

CREATE UNIQUE INDEX player_position_name_key ON public.player_position USING btree (name);

CREATE UNIQUE INDEX player_position_pkey ON public.player_position USING btree (id);

CREATE UNIQUE INDEX profile_id_key ON public.profile USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id, username);

CREATE UNIQUE INDEX profile_position_pkey ON public.profile_position USING btree (id);

CREATE UNIQUE INDEX profile_username_key ON public.profile USING btree (username);

CREATE UNIQUE INDEX unique_profile_position ON public.profile_position USING btree (profile_id, position_id);

CREATE UNIQUE INDEX waitlist_emails_email_key ON public.waitlist_emails USING btree (lower(email));

CREATE UNIQUE INDEX waitlist_emails_pkey ON public.waitlist_emails USING btree (id);

alter table "public"."assistants" add constraint "assistants_pkey" PRIMARY KEY using index "assistants_pkey";

alter table "public"."event" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."eventFeatures" add constraint "eventFeatures_pkey" PRIMARY KEY using index "eventFeatures_pkey";

alter table "public"."eventType" add constraint "eventType_pkey" PRIMARY KEY using index "eventType_pkey";

alter table "public"."features" add constraint "features_pkey" PRIMARY KEY using index "features_pkey";

alter table "public"."level" add constraint "level_pkey" PRIMARY KEY using index "level_pkey";

alter table "public"."otherFeatures" add constraint "otherFeatures_pkey" PRIMARY KEY using index "otherFeatures_pkey";

alter table "public"."paymentMethod" add constraint "paymentMethod_pkey" PRIMARY KEY using index "paymentMethod_pkey";

alter table "public"."player_position" add constraint "player_position_pkey" PRIMARY KEY using index "player_position_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."profile_position" add constraint "profile_position_pkey" PRIMARY KEY using index "profile_position_pkey";

alter table "public"."waitlist_emails" add constraint "waitlist_emails_pkey" PRIMARY KEY using index "waitlist_emails_pkey";

alter table "public"."assistants" add constraint "assistants_event_fkey" FOREIGN KEY (event) REFERENCES public.event(id) not valid;

alter table "public"."assistants" validate constraint "assistants_event_fkey";

alter table "public"."assistants" add constraint "assistants_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."assistants" validate constraint "assistants_user_fkey";

alter table "public"."event" add constraint "event_EventType_fkey" FOREIGN KEY ("EventType") REFERENCES public."eventType"(id) not valid;

alter table "public"."event" validate constraint "event_EventType_fkey";

alter table "public"."event" add constraint "event_created_by_id_fkey" FOREIGN KEY (created_by_id) REFERENCES auth.users(id) not valid;

alter table "public"."event" validate constraint "event_created_by_id_fkey";

alter table "public"."event" add constraint "event_id_key" UNIQUE using index "event_id_key";

alter table "public"."event" add constraint "public_event_level_fkey" FOREIGN KEY (level) REFERENCES public.level(id) not valid;

alter table "public"."event" validate constraint "public_event_level_fkey";

alter table "public"."eventFeatures" add constraint "eventFeatures_event_fkey" FOREIGN KEY (event) REFERENCES public.event(id) not valid;

alter table "public"."eventFeatures" validate constraint "eventFeatures_event_fkey";

alter table "public"."eventFeatures" add constraint "eventFeatures_feature_fkey" FOREIGN KEY (feature) REFERENCES public.features(id) not valid;

alter table "public"."eventFeatures" validate constraint "eventFeatures_feature_fkey";

alter table "public"."eventType" add constraint "public_eventType_event_fkey" FOREIGN KEY (event) REFERENCES public.event(id) not valid;

alter table "public"."eventType" validate constraint "public_eventType_event_fkey";

alter table "public"."level" add constraint "level_name_key" UNIQUE using index "level_name_key";

alter table "public"."otherFeatures" add constraint "otherFeatures_event_fkey" FOREIGN KEY (event) REFERENCES public.event(id) not valid;

alter table "public"."otherFeatures" validate constraint "otherFeatures_event_fkey";

alter table "public"."paymentMethod" add constraint "paymentMethod_event_fkey" FOREIGN KEY (event) REFERENCES public.event(id) not valid;

alter table "public"."paymentMethod" validate constraint "paymentMethod_event_fkey";

alter table "public"."paymentMethod" add constraint "paymentMethod_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."paymentMethod" validate constraint "paymentMethod_user_fkey";

alter table "public"."player_position" add constraint "player_position_id_key" UNIQUE using index "player_position_id_key";

alter table "public"."player_position" add constraint "player_position_name_key" UNIQUE using index "player_position_name_key";

alter table "public"."profile" add constraint "profile_id_key" UNIQUE using index "profile_id_key";

alter table "public"."profile" add constraint "profile_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."profile" validate constraint "profile_user_fkey";

alter table "public"."profile" add constraint "profile_username_key" UNIQUE using index "profile_username_key";

alter table "public"."profile" add constraint "public_profile_level_id_fkey" FOREIGN KEY (level_id) REFERENCES public.level(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "public_profile_level_id_fkey";

alter table "public"."profile_position" add constraint "public_profile_position_position_id_fkey" FOREIGN KEY (position_id) REFERENCES public.player_position(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_position" validate constraint "public_profile_position_position_id_fkey";

alter table "public"."profile_position" add constraint "public_profile_position_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_position" validate constraint "public_profile_position_profile_id_fkey";

alter table "public"."profile_position" add constraint "unique_profile_position" UNIQUE using index "unique_profile_position";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_user_exists(p_email text)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from auth.users u
    where lower(u.email) = lower(p_email)
  );
$function$
;


  create policy "allow_public_insert_waitlist"
  on "public"."waitlist_emails"
  as permissive
  for insert
  to anon, authenticated
with check (true);



