-- TEAM-102: Team memberships and captaincy model.
-- Relates users to teams without storing team ownership directly on profile.

CREATE TABLE IF NOT EXISTS public.team_member (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id     BIGINT NOT NULL REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  role        TEXT NOT NULL DEFAULT 'player',
  status      TEXT NOT NULL DEFAULT 'active',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  joined_at   TIMESTAMPTZ,
  ended_at    TIMESTAMPTZ,

  CONSTRAINT team_member_team_user_unique UNIQUE (team_id, user_id),
  CONSTRAINT team_member_role_check CHECK (role IN ('captain', 'player')),
  CONSTRAINT team_member_status_check CHECK (status IN ('active', 'removed', 'left'))
);

CREATE UNIQUE INDEX IF NOT EXISTS team_member_single_active_captain_idx
  ON public.team_member (team_id)
  WHERE role = 'captain' AND status = 'active';

CREATE INDEX IF NOT EXISTS team_member_user_id_idx
  ON public.team_member (user_id);

CREATE INDEX IF NOT EXISTS team_member_team_id_idx
  ON public.team_member (team_id);

CREATE INDEX IF NOT EXISTS team_member_active_user_id_idx
  ON public.team_member (user_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS team_member_active_team_id_idx
  ON public.team_member (team_id)
  WHERE status = 'active';

CREATE OR REPLACE FUNCTION public.set_team_member_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_team_member_updated_at ON public.team_member;

CREATE TRIGGER set_team_member_updated_at
BEFORE UPDATE ON public.team_member
FOR EACH ROW
EXECUTE FUNCTION public.set_team_member_updated_at();

COMMENT ON TABLE public.team_member IS
  'Membership relation between teams and users. Captaincy is represented as an active membership role.';

COMMENT ON COLUMN public.team_member.team_id IS
  'Team this membership belongs to.';

COMMENT ON COLUMN public.team_member.user_id IS
  'User who belongs to the team.';

COMMENT ON COLUMN public.team_member.role IS
  'Membership role. Allowed values: captain, player.';

COMMENT ON COLUMN public.team_member.status IS
  'Membership lifecycle status. Allowed values: active, removed, left.';

COMMENT ON COLUMN public.team_member.joined_at IS
  'Timestamp when the user became an active member of the team.';

COMMENT ON COLUMN public.team_member.ended_at IS
  'Timestamp when an inactive membership ended. Rows are retained for history.';
