create table if not exists "public"."partner_leads" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "lead_type" text not null,
  "contact_name" text not null,
  "contact_email" text,
  "contact_phone" text,
  "organization_name" text,
  "location_label" text,
  "interest_level" text,
  "budget_range" text,
  "message" text,
  "source" text not null default 'landing_growth_blocks'::text,
  "user_id" uuid,
  "metadata" jsonb not null default '{}'::jsonb,
  "status" text not null default 'new'::text,
  constraint "partner_leads_pkey" primary key ("id"),
  constraint "partner_leads_lead_type_check" check ("lead_type" in ('admin', 'sponsor')),
  constraint "partner_leads_status_check" check ("status" in ('new', 'contacted', 'qualified', 'closed')),
  constraint "partner_leads_user_id_fkey" foreign key ("user_id") references "auth"."users"("id") on update cascade on delete set null
);

create index if not exists "partner_leads_lead_type_idx"
  on "public"."partner_leads" using btree ("lead_type");

create index if not exists "partner_leads_status_created_idx"
  on "public"."partner_leads" using btree ("status", "created_at" desc);

create index if not exists "partner_leads_created_at_idx"
  on "public"."partner_leads" using btree ("created_at" desc);

alter table "public"."partner_leads" enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'partner_leads'
      and policyname = 'partner_leads_public_insert'
  ) then
    create policy "partner_leads_public_insert"
      on "public"."partner_leads"
      as permissive
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'partner_leads'
      and policyname = 'partner_leads_service_role_all'
  ) then
    create policy "partner_leads_service_role_all"
      on "public"."partner_leads"
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
