create table if not exists "public"."ticket" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "assistant_id" bigint not null,
  "event_id" bigint not null,
  "user_id" uuid not null,
  "status" text not null default 'pending',
  "qr_token" text not null,
  "qr_generated_at" timestamp with time zone not null default now(),
  "used_at" timestamp with time zone,
  "apple_wallet_url" text,
  "google_wallet_url" text,
  constraint "ticket_pkey" primary key ("id"),
  constraint "ticket_assistant_id_key" unique ("assistant_id"),
  constraint "ticket_qr_token_key" unique ("qr_token"),
  constraint "ticket_status_check" check (
    "status" in ('pending', 'active', 'used', 'revoked')
  ),
  constraint "ticket_assistant_id_fkey" foreign key ("assistant_id") references "public"."assistants"("id") on update cascade on delete cascade,
  constraint "ticket_event_id_fkey" foreign key ("event_id") references "public"."event"("id") on update cascade on delete cascade,
  constraint "ticket_user_id_fkey" foreign key ("user_id") references "auth"."users"("id") on update cascade on delete cascade
);

create unique index if not exists "ticket_event_user_key" on "public"."ticket" using btree ("event_id", "user_id");
create index if not exists "ticket_user_id_idx" on "public"."ticket" using btree ("user_id");
create index if not exists "ticket_event_id_idx" on "public"."ticket" using btree ("event_id");
