alter table "public"."paymentMethod"
  add column if not exists "name" text,
  add column if not exists "is_active" boolean not null default true,
  add column if not exists "created_by" uuid,
  add column if not exists "updated_by" uuid,
  add column if not exists "updated_at" timestamp with time zone not null default now();

update "public"."paymentMethod"
set "created_by" = "user"
where "created_by" is null
  and "user" is not null;

update "public"."paymentMethod"
set "type" = case
  when coalesce(lower("type"), '') like '%yape%' and coalesce(lower("type"), '') like '%plin%' then 'yape_plin'
  when coalesce(lower("type"), '') like '%plin%' then 'plin'
  when coalesce(lower("type"), '') like '%yape%' then 'yape'
  else 'yape'
end;

update "public"."paymentMethod"
set "name" = concat_ws(' ', 'Método', "id"::text)
where coalesce(btrim("name"), '') = '';

alter table "public"."paymentMethod"
  alter column "type" set default 'yape',
  alter column "type" set not null;

alter table "public"."paymentMethod"
  drop constraint if exists "paymentMethod_type_check";

alter table "public"."paymentMethod"
  add constraint "paymentMethod_type_check"
  check ("type" in ('yape', 'plin', 'yape_plin'));

alter table "public"."paymentMethod"
  drop constraint if exists "paymentMethod_created_by_fkey";

alter table "public"."paymentMethod"
  add constraint "paymentMethod_created_by_fkey"
  foreign key ("created_by") references "auth"."users"("id") on update cascade on delete set null;

alter table "public"."paymentMethod"
  drop constraint if exists "paymentMethod_updated_by_fkey";

alter table "public"."paymentMethod"
  add constraint "paymentMethod_updated_by_fkey"
  foreign key ("updated_by") references "auth"."users"("id") on update cascade on delete set null;

create index if not exists "paymentMethod_is_active_idx"
  on "public"."paymentMethod" using btree ("is_active");

create table if not exists "public"."eventPaymentMethod" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "event" bigint not null,
  "paymentMethod" bigint not null,
  constraint "eventPaymentMethod_pkey" primary key ("id"),
  constraint "eventPaymentMethod_event_fkey"
    foreign key ("event") references "public"."event"("id") on update cascade on delete cascade,
  constraint "eventPaymentMethod_paymentMethod_fkey"
    foreign key ("paymentMethod") references "public"."paymentMethod"("id") on update cascade on delete cascade,
  constraint "eventPaymentMethod_event_paymentMethod_key" unique ("event", "paymentMethod")
);

create index if not exists "eventPaymentMethod_event_idx"
  on "public"."eventPaymentMethod" using btree ("event");

create index if not exists "eventPaymentMethod_paymentMethod_idx"
  on "public"."eventPaymentMethod" using btree ("paymentMethod");

insert into "public"."eventPaymentMethod" ("event", "paymentMethod")
select distinct "event", "id"
from "public"."paymentMethod"
where "event" is not null
on conflict ("event", "paymentMethod") do nothing;

alter table "public"."paymentMethod"
  drop constraint if exists "paymentMethod_event_fkey";

alter table "public"."paymentMethod"
  drop constraint if exists "paymentMethod_user_fkey";

alter table "public"."paymentMethod"
  drop column if exists "event",
  drop column if exists "user";
