-- TEAM-104 hardening: idempotent team creation requests.
-- Protects the creation flow from duplicate POST retries that carry the same
-- client-generated idempotency key.

CREATE TABLE IF NOT EXISTS public.team_creation_request (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  idempotency_key TEXT NOT NULL,
  team_id         BIGINT REFERENCES public.team(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT team_creation_request_key_format
    CHECK (idempotency_key ~ '^[A-Za-z0-9._:-]{8,128}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS team_creation_request_user_key_unique_idx
  ON public.team_creation_request (user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS team_creation_request_team_id_idx
  ON public.team_creation_request (team_id);

CREATE OR REPLACE FUNCTION public.set_team_creation_request_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_team_creation_request_updated_at ON public.team_creation_request;

CREATE TRIGGER set_team_creation_request_updated_at
BEFORE UPDATE ON public.team_creation_request
FOR EACH ROW
EXECUTE FUNCTION public.set_team_creation_request_updated_at();

COMMENT ON TABLE public.team_creation_request IS
  'Internal idempotency ledger for team creation requests.';

COMMENT ON COLUMN public.team_creation_request.idempotency_key IS
  'Client-generated retry key scoped to the authenticated creator.';

COMMENT ON COLUMN public.team_creation_request.team_id IS
  'Team created for this idempotent request, once the transaction succeeds.';

ALTER TABLE public.team_creation_request ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.team_creation_request TO service_role;
REVOKE ALL ON public.team_creation_request FROM anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'team_creation_request'
      AND policyname = 'team_creation_request_service_role_all'
  ) THEN
    CREATE POLICY team_creation_request_service_role_all
      ON public.team_creation_request
      AS PERMISSIVE
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DROP FUNCTION IF EXISTS public.create_team_with_captain(TEXT, TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.create_team_with_captain(
  p_name TEXT,
  p_avatar_url TEXT DEFAULT NULL,
  p_instagram_username TEXT DEFAULT NULL,
  p_tiktok_username TEXT DEFAULT NULL,
  p_idempotency_key TEXT DEFAULT NULL
)
RETURNS SETOF public.team
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_name TEXT := btrim(COALESCE(p_name, ''));
  v_idempotency_key TEXT := NULLIF(btrim(COALESCE(p_idempotency_key, '')), '');
  v_request_id BIGINT;
  v_existing_team_id BIGINT;
  v_team public.team%ROWTYPE;
  v_attempt INTEGER := 0;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '28000';
  END IF;

  IF char_length(v_name) < 2 OR char_length(v_name) > 80 THEN
    RAISE EXCEPTION 'Team name must be between 2 and 80 characters' USING ERRCODE = '23514';
  END IF;

  IF v_idempotency_key IS NOT NULL
    AND v_idempotency_key !~ '^[A-Za-z0-9._:-]{8,128}$'
  THEN
    RAISE EXCEPTION 'Invalid idempotency key' USING ERRCODE = '23514';
  END IF;

  IF v_idempotency_key IS NOT NULL THEN
    INSERT INTO public.team_creation_request (
      user_id,
      idempotency_key
    )
    VALUES (
      v_user_id,
      v_idempotency_key
    )
    ON CONFLICT (user_id, idempotency_key) DO NOTHING
    RETURNING id
    INTO v_request_id;

    IF v_request_id IS NULL THEN
      SELECT id, team_id
      INTO v_request_id, v_existing_team_id
      FROM public.team_creation_request
      WHERE user_id = v_user_id
        AND idempotency_key = v_idempotency_key
      FOR UPDATE;

      IF v_existing_team_id IS NOT NULL THEN
        RETURN QUERY
        SELECT *
        FROM public.team existing_team
        WHERE existing_team.id = v_existing_team_id;
        RETURN;
      END IF;
    END IF;
  END IF;

  LOOP
    BEGIN
      INSERT INTO public.team (
        name,
        slug,
        avatar_url,
        instagram_username,
        tiktok_username,
        created_by_user_id
      )
      VALUES (
        v_name,
        public.generate_unique_team_slug(v_name),
        NULLIF(btrim(p_avatar_url), ''),
        NULLIF(btrim(p_instagram_username), ''),
        NULLIF(btrim(p_tiktok_username), ''),
        v_user_id
      )
      RETURNING * INTO v_team;
      EXIT;
    EXCEPTION
      WHEN unique_violation THEN
        v_attempt := v_attempt + 1;
        IF v_attempt >= 5 THEN
          RAISE;
        END IF;
    END;
  END LOOP;

  INSERT INTO public.team_member (
    team_id,
    user_id,
    role,
    status,
    joined_at
  )
  VALUES (
    v_team.id,
    v_user_id,
    'captain',
    'active',
    now()
  );

  IF v_request_id IS NOT NULL THEN
    UPDATE public.team_creation_request
    SET team_id = v_team.id
    WHERE id = v_request_id;
  END IF;

  RETURN QUERY
  SELECT *
  FROM public.team created_team
  WHERE created_team.id = v_team.id;
END;
$$;

COMMENT ON FUNCTION public.create_team_with_captain(TEXT, TEXT, TEXT, TEXT, TEXT) IS
  'Atomically creates a team and captain membership, returning the same team for repeated idempotency keys.';

REVOKE ALL ON FUNCTION public.create_team_with_captain(TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_team_with_captain(TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
