create table if not exists "public"."event_announcement" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "event_id" bigint not null,
  "created_by_user_id" uuid,
  "subject" text not null,
  "body" text not null,
  "total_recipients" integer not null default 0,
  "sent_count" integer not null default 0,
  "failed_count" integer not null default 0,
  "status" text not null default 'completed'::text,
  "source_announcement_id" bigint,
  constraint "event_announcement_pkey" primary key ("id"),
  constraint "event_announcement_event_id_fkey"
    foreign key ("event_id") references "public"."event"("id")
    on update cascade on delete cascade,
  constraint "event_announcement_created_by_user_id_fkey"
    foreign key ("created_by_user_id") references "auth"."users"("id")
    on update cascade on delete set null,
  constraint "event_announcement_source_announcement_id_fkey"
    foreign key ("source_announcement_id") references "public"."event_announcement"("id")
    on update cascade on delete set null,
  constraint "event_announcement_status_check"
    check ("status" in ('completed', 'partial', 'failed'))
);

create index if not exists "event_announcement_event_created_idx"
  on "public"."event_announcement" using btree ("event_id", "created_at" desc);

create index if not exists "event_announcement_source_idx"
  on "public"."event_announcement" using btree ("source_announcement_id");

create table if not exists "public"."event_announcement_recipient" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "announcement_id" bigint not null,
  "event_id" bigint not null,
  "recipient_user_id" uuid,
  "recipient_name" text,
  "recipient_email" text not null,
  "participant_state" text,
  "status" text not null,
  "provider_message_id" text,
  "error_message" text,
  constraint "event_announcement_recipient_pkey" primary key ("id"),
  constraint "event_announcement_recipient_announcement_id_fkey"
    foreign key ("announcement_id") references "public"."event_announcement"("id")
    on update cascade on delete cascade,
  constraint "event_announcement_recipient_event_id_fkey"
    foreign key ("event_id") references "public"."event"("id")
    on update cascade on delete cascade,
  constraint "event_announcement_recipient_user_id_fkey"
    foreign key ("recipient_user_id") references "auth"."users"("id")
    on update cascade on delete set null,
  constraint "event_announcement_recipient_status_check"
    check ("status" in ('queued', 'failed'))
);

create index if not exists "event_announcement_recipient_announcement_status_idx"
  on "public"."event_announcement_recipient" using btree ("announcement_id", "status");

create index if not exists "event_announcement_recipient_event_created_idx"
  on "public"."event_announcement_recipient" using btree ("event_id", "created_at" desc);

alter table "public"."event_announcement" enable row level security;
alter table "public"."event_announcement_recipient" enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'event_announcement'
      and policyname = 'event_announcement_service_role_all'
  ) then
    create policy "event_announcement_service_role_all"
      on "public"."event_announcement"
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'event_announcement_recipient'
      and policyname = 'event_announcement_recipient_service_role_all'
  ) then
    create policy "event_announcement_recipient_service_role_all"
      on "public"."event_announcement_recipient"
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
