create table if not exists "public"."event_ticket_reminder_delivery" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "event_id" bigint not null,
  "assistant_id" bigint not null,
  "recipient_user_id" uuid not null,
  "recipient_email" text not null,
  "reminder_type" text not null,
  "status" text not null default 'processing',
  "provider_message_id" text,
  "error_message" text,
  "sent_at" timestamp with time zone,
  "last_attempt_at" timestamp with time zone not null default now(),
  constraint "event_ticket_reminder_delivery_pkey" primary key ("id"),
  constraint "event_ticket_reminder_delivery_event_id_fkey"
    foreign key ("event_id") references "public"."event"("id")
    on delete cascade,
  constraint "event_ticket_reminder_delivery_assistant_id_fkey"
    foreign key ("assistant_id") references "public"."assistants"("id")
    on delete cascade,
  constraint "event_ticket_reminder_delivery_reminder_type_check"
    check ("reminder_type" = 'event_starts_in_1_hour'),
  constraint "event_ticket_reminder_delivery_status_check"
    check ("status" in ('processing', 'sent', 'failed'))
);

create unique index if not exists "event_ticket_reminder_delivery_unique_idx"
  on "public"."event_ticket_reminder_delivery" using btree ("event_id", "recipient_user_id", "reminder_type");

create index if not exists "event_ticket_reminder_delivery_status_idx"
  on "public"."event_ticket_reminder_delivery" using btree ("status", "last_attempt_at" desc);

alter table "public"."event_ticket_reminder_delivery" enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'event_ticket_reminder_delivery'
      and policyname = 'event_ticket_reminder_delivery_service_role_all'
  ) then
    create policy "event_ticket_reminder_delivery_service_role_all"
      on "public"."event_ticket_reminder_delivery"
      for all
      to "service_role"
      using (true)
      with check (true);
  end if;
end
$$;
