-- TEAM-101: Core team profile model.
-- Stores the public identity of a team independently from memberships/captaincy.

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.team (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  name                TEXT NOT NULL,
  slug                TEXT NOT NULL,
  avatar_url          TEXT,
  instagram_username  TEXT,
  tiktok_username     TEXT,
  created_by_user_id  UUID NOT NULL REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  invitation_token    UUID NOT NULL DEFAULT extensions.gen_random_uuid(),
  is_active           BOOLEAN NOT NULL DEFAULT true,
  deleted_at          TIMESTAMPTZ,

  CONSTRAINT team_name_length
    CHECK (char_length(btrim(name)) BETWEEN 2 AND 80),
  CONSTRAINT team_slug_format
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX IF NOT EXISTS team_slug_unique_idx
  ON public.team (slug);

CREATE UNIQUE INDEX IF NOT EXISTS team_invitation_token_unique_idx
  ON public.team (invitation_token);

CREATE INDEX IF NOT EXISTS team_created_by_user_id_idx
  ON public.team (created_by_user_id);

CREATE INDEX IF NOT EXISTS team_active_slug_idx
  ON public.team (slug)
  WHERE is_active = true AND deleted_at IS NULL;

CREATE OR REPLACE FUNCTION public.set_team_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_team_updated_at ON public.team;

CREATE TRIGGER set_team_updated_at
BEFORE UPDATE ON public.team
FOR EACH ROW
EXECUTE FUNCTION public.set_team_updated_at();

COMMENT ON TABLE public.team IS
  'Public team profile data. Captaincy and player membership are stored separately.';

COMMENT ON COLUMN public.team.name IS
  'Required display name. Trimmed length must be between 2 and 80 characters.';

COMMENT ON COLUMN public.team.slug IS
  'Unique public URL slug using lowercase letters, numbers and hyphens.';

COMMENT ON COLUMN public.team.avatar_url IS
  'Public URL for the team avatar image.';

COMMENT ON COLUMN public.team.instagram_username IS
  'Optional Instagram username for the team, without enforcing display formatting.';

COMMENT ON COLUMN public.team.tiktok_username IS
  'Optional TikTok username for the team, without enforcing display formatting.';

COMMENT ON COLUMN public.team.created_by_user_id IS
  'Historical creator of the team. This remains stable even if captaincy changes later.';

COMMENT ON COLUMN public.team.invitation_token IS
  'Unique token generated at creation time for the future team invitation link flow.';

COMMENT ON COLUMN public.team.is_active IS
  'Fast active/inactive flag for team visibility and future administrative workflows.';

COMMENT ON COLUMN public.team.deleted_at IS
  'Logical deletion timestamp. Rows should not be physically removed by product flows.';
