-- Sync the old Supabase project schema to match the current public schema
-- that is already present in the new development project as of 2026-03-12.
--
-- Intentionally excluded:
-- - partner_leads: present in local migrations, but not present in the new
--   remote project during verification.
-- - teams/team_members/team_invites/users_view: referenced in code, but not
--   present in either verified remote project.

begin;

alter table public.event
add column if not exists is_featured boolean not null default false;

create index if not exists event_is_featured_start_time_idx
on public.event (is_featured, start_time);

create table if not exists public.ticket (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  assistant_id bigint not null,
  event_id bigint not null,
  user_id uuid not null,
  status text not null default 'pending',
  qr_token text not null,
  qr_generated_at timestamp with time zone not null default now(),
  used_at timestamp with time zone,
  apple_wallet_url text,
  google_wallet_url text,
  constraint ticket_pkey primary key (id),
  constraint ticket_assistant_id_key unique (assistant_id),
  constraint ticket_qr_token_key unique (qr_token),
  constraint ticket_status_check check (status in ('pending', 'active', 'used', 'revoked')),
  constraint ticket_assistant_id_fkey
    foreign key (assistant_id) references public.assistants (id)
    on update cascade on delete cascade,
  constraint ticket_event_id_fkey
    foreign key (event_id) references public.event (id)
    on update cascade on delete cascade,
  constraint ticket_user_id_fkey
    foreign key (user_id) references auth.users (id)
    on update cascade on delete cascade
);

create unique index if not exists ticket_event_user_key
  on public.ticket using btree (event_id, user_id);

create index if not exists ticket_user_id_idx
  on public.ticket using btree (user_id);

create index if not exists ticket_event_id_idx
  on public.ticket using btree (event_id);

create table if not exists public.wallet_provider_settings (
  id bigint generated by default as identity not null,
  provider text not null,
  issuer_id text not null,
  active_class_id text,
  service_account_email text not null,
  service_account_private_key text not null,
  origins text[] not null default '{}'::text[],
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  constraint wallet_provider_settings_pkey primary key (id),
  constraint wallet_provider_settings_provider_key unique (provider),
  constraint wallet_provider_settings_provider_check check (provider in ('google_wallet')),
  constraint wallet_provider_settings_updated_by_fkey
    foreign key (updated_by) references auth.users (id)
    on update cascade on delete set null
);

create index if not exists wallet_provider_settings_provider_idx
  on public.wallet_provider_settings using btree (provider);

alter table public.wallet_provider_settings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'wallet_provider_settings'
      and policyname = 'wallet_provider_settings_service_role_all'
  ) then
    create policy wallet_provider_settings_service_role_all
      on public.wallet_provider_settings
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

alter table public."paymentMethod"
  add column if not exists name text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_by uuid,
  add column if not exists updated_by uuid,
  add column if not exists updated_at timestamp with time zone not null default now();

update public."paymentMethod"
set created_by = "user"
where created_by is null
  and "user" is not null;

update public."paymentMethod"
set type = case
  when coalesce(lower(type), '') like '%yape%' and coalesce(lower(type), '') like '%plin%' then 'yape_plin'
  when coalesce(lower(type), '') like '%plin%' then 'plin'
  when coalesce(lower(type), '') like '%yape%' then 'yape'
  else 'yape'
end;

update public."paymentMethod"
set name = concat_ws(' ', 'Método', id::text)
where coalesce(btrim(name), '') = '';

alter table public."paymentMethod"
  alter column type set default 'yape',
  alter column type set not null;

alter table public."paymentMethod"
  drop constraint if exists "paymentMethod_type_check";

alter table public."paymentMethod"
  add constraint "paymentMethod_type_check"
  check (type in ('yape', 'plin', 'yape_plin'));

alter table public."paymentMethod"
  drop constraint if exists "paymentMethod_created_by_fkey";

alter table public."paymentMethod"
  add constraint "paymentMethod_created_by_fkey"
  foreign key (created_by) references auth.users (id)
  on update cascade on delete set null;

alter table public."paymentMethod"
  drop constraint if exists "paymentMethod_updated_by_fkey";

alter table public."paymentMethod"
  add constraint "paymentMethod_updated_by_fkey"
  foreign key (updated_by) references auth.users (id)
  on update cascade on delete set null;

create index if not exists "paymentMethod_is_active_idx"
  on public."paymentMethod" using btree (is_active);

create table if not exists public."eventPaymentMethod" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  event bigint not null,
  "paymentMethod" bigint not null,
  constraint "eventPaymentMethod_pkey" primary key (id),
  constraint "eventPaymentMethod_event_fkey"
    foreign key (event) references public.event (id)
    on update cascade on delete cascade,
  constraint "eventPaymentMethod_paymentMethod_fkey"
    foreign key ("paymentMethod") references public."paymentMethod" (id)
    on update cascade on delete cascade,
  constraint "eventPaymentMethod_event_paymentMethod_key" unique (event, "paymentMethod")
);

create index if not exists "eventPaymentMethod_event_idx"
  on public."eventPaymentMethod" using btree (event);

create index if not exists "eventPaymentMethod_paymentMethod_idx"
  on public."eventPaymentMethod" using btree ("paymentMethod");

insert into public."eventPaymentMethod" (event, "paymentMethod")
select distinct event, id
from public."paymentMethod"
where event is not null
on conflict (event, "paymentMethod") do nothing;

alter table public."paymentMethod"
  drop constraint if exists "paymentMethod_event_fkey";

alter table public."paymentMethod"
  drop constraint if exists "paymentMethod_user_fkey";

alter table public."paymentMethod"
  drop column if exists event,
  drop column if exists "user";

create table if not exists public.product_analytics_events (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  event_name text not null,
  user_id uuid,
  event_id bigint,
  ref_user_id uuid,
  source text not null default 'web'::text,
  channel text,
  user_agent text,
  ip_address text,
  payload jsonb not null default '{}'::jsonb,
  constraint product_analytics_events_pkey primary key (id),
  constraint product_analytics_events_user_id_fkey
    foreign key (user_id) references auth.users (id)
    on update cascade on delete set null,
  constraint product_analytics_events_ref_user_id_fkey
    foreign key (ref_user_id) references auth.users (id)
    on update cascade on delete set null,
  constraint product_analytics_events_event_id_fkey
    foreign key (event_id) references public.event (id)
    on update cascade on delete set null
);

create index if not exists product_analytics_events_event_name_idx
  on public.product_analytics_events using btree (event_name);

create index if not exists product_analytics_events_created_at_idx
  on public.product_analytics_events using btree (created_at desc);

create index if not exists product_analytics_events_event_id_idx
  on public.product_analytics_events using btree (event_id);

create index if not exists product_analytics_events_ref_user_id_idx
  on public.product_analytics_events using btree (ref_user_id);

alter table public.product_analytics_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'product_analytics_events'
      and policyname = 'product_analytics_events_public_insert'
  ) then
    create policy product_analytics_events_public_insert
      on public.product_analytics_events
      as permissive
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'product_analytics_events'
      and policyname = 'product_analytics_events_service_role_all'
  ) then
    create policy product_analytics_events_service_role_all
      on public.product_analytics_events
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

alter table public.event
  add column if not exists is_published boolean not null default true;

create index if not exists event_is_published_start_time_idx
  on public.event using btree (is_published, start_time);

create table if not exists public.event_announcement (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  event_id bigint not null,
  created_by_user_id uuid,
  subject text not null,
  body text not null,
  body_html text,
  total_recipients integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  status text not null default 'completed'::text,
  source_announcement_id bigint,
  constraint event_announcement_pkey primary key (id),
  constraint event_announcement_event_id_fkey
    foreign key (event_id) references public.event (id)
    on update cascade on delete cascade,
  constraint event_announcement_created_by_user_id_fkey
    foreign key (created_by_user_id) references auth.users (id)
    on update cascade on delete set null,
  constraint event_announcement_source_announcement_id_fkey
    foreign key (source_announcement_id) references public.event_announcement (id)
    on update cascade on delete set null,
  constraint event_announcement_status_check
    check (status in ('completed', 'partial', 'failed'))
);

create index if not exists event_announcement_event_created_idx
  on public.event_announcement using btree (event_id, created_at desc);

create index if not exists event_announcement_source_idx
  on public.event_announcement using btree (source_announcement_id);

create table if not exists public.event_announcement_recipient (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  announcement_id bigint not null,
  event_id bigint not null,
  recipient_user_id uuid,
  recipient_name text,
  recipient_email text not null,
  participant_state text,
  status text not null,
  provider_message_id text,
  error_message text,
  constraint event_announcement_recipient_pkey primary key (id),
  constraint event_announcement_recipient_announcement_id_fkey
    foreign key (announcement_id) references public.event_announcement (id)
    on update cascade on delete cascade,
  constraint event_announcement_recipient_event_id_fkey
    foreign key (event_id) references public.event (id)
    on update cascade on delete cascade,
  constraint event_announcement_recipient_user_id_fkey
    foreign key (recipient_user_id) references auth.users (id)
    on update cascade on delete set null,
  constraint event_announcement_recipient_status_check
    check (status in ('queued', 'failed'))
);

create index if not exists event_announcement_recipient_announcement_status_idx
  on public.event_announcement_recipient using btree (announcement_id, status);

create index if not exists event_announcement_recipient_event_created_idx
  on public.event_announcement_recipient using btree (event_id, created_at desc);

alter table public.event_announcement enable row level security;
alter table public.event_announcement_recipient enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'event_announcement'
      and policyname = 'event_announcement_service_role_all'
  ) then
    create policy event_announcement_service_role_all
      on public.event_announcement
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'event_announcement_recipient'
      and policyname = 'event_announcement_recipient_service_role_all'
  ) then
    create policy event_announcement_recipient_service_role_all
      on public.event_announcement_recipient
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

commit;
